name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      # CHECKOUT
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # NODE VERSION
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # BACKEND
      - name: Instalar dependencias backend
        working-directory: inventory-api
        run: npm install

      - name: Lint backend
        working-directory: inventory-api
        run: npm run lint

      - name: Tests backend (unitarias + integración)
        working-directory: inventory-api
        env:
          NODE_ENV: test
        run: npm test

      # FRONTEND
      - name: Instalar dependencias frontend
        working-directory: inventory-frontend
        run: |
          npm install
          npm install --save-dev wait-on

      - name: Lint frontend
        working-directory: inventory-frontend
        run: npm run lint

      # PLAYWRIGHT (E2E)
      - name: Instalar navegadores de Playwright
        working-directory: inventory-frontend
        run: npx playwright install --with-deps

      # BACKEND 
      - name: Iniciar backend
        working-directory: inventory-api
        run: |
          npm start &
          echo " Backend iniciado"
          npx wait-on http://localhost:3000
          echo "Backend OK ✔"

      # FRONTEND → build + preview
      
      - name: Build frontend
        working-directory: inventory-frontend
        run: npm run build

      - name: Iniciar servidor preview frontend
        working-directory: inventory-frontend
        run: |
          npm run preview -- --host 0.0.0.0 --port 5173 &
          echo " Frontend iniciando..."
          npx wait-on http://localhost:5173
          echo "Frontend OK ✔"

      
      # E2E
      - name: Ejecutar tests E2E
        working-directory: inventory-frontend
        run: npm run test:e2e

      # FINAL
      - name: Imprimir OK si todo pasó
        run: echo "OK ✔ Todos los checks pasaron correctamente."